poniedziałek, 28 stycznia 2019 09:02:33

Zgłoszenie ZCC-17932 dodano automatycznie o godzinie 2019-01-28 09:02:33!
poniedziałek, 28 stycznia 2019 09:02:36

addCommentJira string jiraKey ZCC-17932poniedziałek, 28 stycznia 2019 09:02:36

addCommentJira object sender, DoWorkEventArgs e ZCC-17932poniedziałek, 28 stycznia 2019 09:32:41

Zgłoszenie CRM-75059 dodano automatycznie o godzinie 2019-01-28 09:32:41!
poniedziałek, 28 stycznia 2019 09:32:43

addCommentJira string jiraKey CRM-75059poniedziałek, 28 stycznia 2019 09:32:43

addCommentJira object sender, DoWorkEventArgs e CRM-75059poniedziałek, 28 stycznia 2019 09:50:04

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:05

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:05

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:06

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:07

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:07

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:08

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:08

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:09

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:09

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:10

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:11

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:11

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:12

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:12

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:15

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:16

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:16

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:17

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:17

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:18

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:19

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:19

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:20

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:20

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:21

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:50:22

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 560

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 09:56:32

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17930 - 312130poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera WIND-7763

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera WIND-7744

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera WIND-8044

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-74952

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75042

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17929

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17931

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75024

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17923

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera INFOLINIA-6464

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75038

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75039

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75041

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75047

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75048

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75057

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17932

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17919

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17916

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17917

poniedziałek, 28 stycznia 2019 10:06:57

selectIssueList nie zawiera ZCC-17924

poniedziałek, 28 stycznia 2019 10:06:58

selectIssueList nie zawiera LIDKA-120

poniedziałek, 28 stycznia 2019 10:06:58

selectIssueList nie zawiera WIND-8056

poniedziałek, 28 stycznia 2019 10:06:58

selectIssueList nie zawiera KKK-3893

poniedziałek, 28 stycznia 2019 10:06:59

selectIssueList nie zawiera CRM-75045

poniedziałek, 28 stycznia 2019 10:06:59

selectIssueList nie zawiera CRM-75053

poniedziałek, 28 stycznia 2019 10:06:59

selectIssueList nie zawiera CRM-75044

poniedziałek, 28 stycznia 2019 10:06:59

selectIssueList nie zawiera CRM-75054

poniedziałek, 28 stycznia 2019 10:12:46

selectIssueList nie zawiera ZCC-17931

poniedziałek, 28 stycznia 2019 10:12:46

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:28:13

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:28:13

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:28:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e)

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 10:28:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e)

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 10:28:20

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e)

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 10:28:20

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e)

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 10:28:41

Zgłoszenie CRM-75060 dodano automatycznie o godzinie 2019-01-28 10:28:41!
poniedziałek, 28 stycznia 2019 10:28:44

addCommentJira string jiraKey CRM-75060poniedziałek, 28 stycznia 2019 10:28:44

addCommentJira object sender, DoWorkEventArgs e CRM-75060poniedziałek, 28 stycznia 2019 10:28:46

Zgłoszenie CRM-75061 dodano automatycznie o godzinie 2019-01-28 10:28:46!
poniedziałek, 28 stycznia 2019 10:29:08

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:29:08

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:29:12

addCommentJira string jiraKey CRM-75061poniedziałek, 28 stycznia 2019 10:29:12

addCommentJira object sender, DoWorkEventArgs e CRM-75061poniedziałek, 28 stycznia 2019 10:33:29

Zgłoszenie CRM-75063 dodano automatycznie o godzinie 2019-01-28 10:33:29!
poniedziałek, 28 stycznia 2019 10:33:31

addCommentJira string jiraKey CRM-75063poniedziałek, 28 stycznia 2019 10:33:32

addCommentJira object sender, DoWorkEventArgs e CRM-75063poniedziałek, 28 stycznia 2019 10:33:39

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:33:42

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:34:18

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:34:26

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:39:50

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 10:39:52

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:39:52

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:45:25

Zgłoszenie CRM-75062 dodano automatycznie o godzinie 2019-01-28 10:45:25!
poniedziałek, 28 stycznia 2019 10:45:28

addCommentJira string jiraKey CRM-75062poniedziałek, 28 stycznia 2019 10:45:28

addCommentJira object sender, DoWorkEventArgs e CRM-75062poniedziałek, 28 stycznia 2019 10:45:47

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 10:45:47

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:45:47

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:51:53

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 10:51:53

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:51:53

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 10:57:57

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 10:57:58

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 10:57:59

selectIssueList nie zawiera CRM-75059

poniedziałek, 28 stycznia 2019 11:03:55

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 11:03:55

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 11:09:42

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 11:09:57

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 11:15:54

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 11:15:54

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 11:21:50

selectIssueList nie zawiera ZCC-17930

poniedziałek, 28 stycznia 2019 11:21:50

selectIssueList nie zawiera CRM-75063

poniedziałek, 28 stycznia 2019 11:54:05

Zgłoszenie ZCC-17935 dodano automatycznie o godzinie 2019-01-28 11:54:05!
poniedziałek, 28 stycznia 2019 11:54:07

addCommentJira string jiraKey ZCC-17935poniedziałek, 28 stycznia 2019 11:54:07

addCommentJira object sender, DoWorkEventArgs e ZCC-17935poniedziałek, 28 stycznia 2019 11:54:12

Zgłoszenie ZCC-17936 dodano automatycznie o godzinie 2019-01-28 11:54:12!
poniedziałek, 28 stycznia 2019 11:54:38

addCommentJira string jiraKey ZCC-17936poniedziałek, 28 stycznia 2019 11:54:38

addCommentJira object sender, DoWorkEventArgs e ZCC-17936poniedziałek, 28 stycznia 2019 12:00:38

selectIssueList nie zawiera ZCC-17932

poniedziałek, 28 stycznia 2019 12:00:38

selectIssueList nie zawiera ZCC-17936

poniedziałek, 28 stycznia 2019 12:00:38

selectIssueList nie zawiera ZCC-17935

poniedziałek, 28 stycznia 2019 12:17:52

Zgłoszenie CRM-75067 dodano automatycznie o godzinie 2019-01-28 12:17:52!
poniedziałek, 28 stycznia 2019 12:30:32

--- Main exception: Message ---
Nie można uzyskać dostępu do usuniętego obiektu.
Nazwa obiektu: 'WFSform'.

--- Main exception: StackTrace ---
   w System.Windows.Forms.Control.CreateHandle()
   w System.Windows.Forms.Form.CreateHandle()
   w System.Windows.Forms.Control.get_Handle()
   w System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   w System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   w System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   w GUI.MainForm.UzupelnijDane(TreeView tr, Boolean auto) w C:\CP\ParserGit\JiraParser\GUI\MainForm.cs:wiersz 3766
   w GUI.MainForm.<newIssueAutoAddToBPMUzupelnijDane>b__221_0() w C:\CP\ParserGit\JiraParser\GUI\MainForm.cs:wiersz 7340

--- Main exception: Source ---
System.Windows.Forms

poniedziałek, 28 stycznia 2019 12:30:40

addCommentJira string jiraKey CRM-75067poniedziałek, 28 stycznia 2019 12:30:40

addCommentJira object sender, DoWorkEventArgs e CRM-75067poniedziałek, 28 stycznia 2019 12:35:53

Zgłoszenie CRM-75068 dodano automatycznie o godzinie 2019-01-28 12:35:53!
poniedziałek, 28 stycznia 2019 12:35:55

addCommentJira string jiraKey CRM-75068poniedziałek, 28 stycznia 2019 12:35:55

addCommentJira object sender, DoWorkEventArgs e CRM-75068poniedziałek, 28 stycznia 2019 12:35:57

Zgłoszenie CRM-75069 dodano automatycznie o godzinie 2019-01-28 12:35:57!
poniedziałek, 28 stycznia 2019 12:36:23

addCommentJira string jiraKey CRM-75069poniedziałek, 28 stycznia 2019 12:36:23

addCommentJira object sender, DoWorkEventArgs e CRM-75069poniedziałek, 28 stycznia 2019 12:44:22

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 12:52:47

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 12:54:18

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:02:23

selectIssueList nie zawiera CRM-75069

poniedziałek, 28 stycznia 2019 13:02:24

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 13:02:27

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:05:51

Zgłoszenie ZCC-17938 dodano automatycznie o godzinie 2019-01-28 13:05:51!
poniedziałek, 28 stycznia 2019 13:05:59

addCommentJira string jiraKey ZCC-17938poniedziałek, 28 stycznia 2019 13:05:59

addCommentJira object sender, DoWorkEventArgs e ZCC-17938poniedziałek, 28 stycznia 2019 13:06:49

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 13:06:49

selectIssueList nie zawiera CRM-75069

poniedziałek, 28 stycznia 2019 13:06:56

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:12:54

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 13:12:54

selectIssueList nie zawiera CRM-75069

poniedziałek, 28 stycznia 2019 13:12:54

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:18:13

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 13:18:13

selectIssueList nie zawiera CRM-75069

poniedziałek, 28 stycznia 2019 13:18:13

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:28:06

--- Main exception: Message ---
Nie można rozpoznać nazwy zdalnej: 'jira'

--- Main exception: StackTrace ---
   w Atlassian.Jira.Remote.JiraRestClient.ExecuteRequest(Method method, String resource, Object requestBody) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 107
   w Atlassian.Jira.Remote.JiraRestClient.GetIssuesFromFilterWithLimit(String token, String filterId, Int32 offset, Int32 maxResults) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 846
   w Atlassian.Jira.Jira.<>c__DisplayClass5.<GetIssuesFromFilter>b__3(String token) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 296
   w Atlassian.Jira.Jira.WithToken[TResult](Func`3 function) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 706
   w Atlassian.Jira.Jira.GetIssuesFromFilter(String filterName, Int32 start, Nullable`1 maxResults) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 294
   w Logic.Implementation.JiraIssues.GetIssuesFromFilterAsync(String filterName) w C:\CP\ParserGit\JiraParser\Logic\Implementation\JiraIssues.cs:wiersz 803
   w GUI.MainForm.<timer2_Tick>b__101_0() w C:\CP\ParserGit\JiraParser\GUI\MainForm.cs:wiersz 2676

--- Main exception: Source ---
Atlassian.Jira

poniedziałek, 28 stycznia 2019 13:28:07

--- Main exception: Message ---
Nie można rozpoznać nazwy zdalnej: 'jira'

--- Main exception: StackTrace ---
   w Atlassian.Jira.Remote.JiraRestClient.ExecuteRequest[T](Method method, String resource, Object requestBody) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 119
   w Atlassian.Jira.Remote.JiraRestClient.GetIssueTypes(String token, String projectId) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 822
   w Atlassian.Jira.Jira.<>c__DisplayClass16.<GetIssueTypes>b__12(String token) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 414
   w Atlassian.Jira.Jira.<>c__DisplayClass3c.<WithToken>b__3b(String t) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 658
   w Atlassian.Jira.Jira.WithToken[TResult](Func`3 function) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 706
   w Atlassian.Jira.Jira.GetIssueTypes(String projectKey) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 419
   w Logic.Implementation.JiraIssues.GetJiraIssuesTypes() w C:\CP\ParserGit\JiraParser\Logic\Implementation\JiraIssues.cs:wiersz 68
   w GUI.MainForm.<timer2_Tick>b__101_0() w C:\CP\ParserGit\JiraParser\GUI\MainForm.cs:wiersz 2658

--- Main exception: Source ---
Atlassian.Jira

poniedziałek, 28 stycznia 2019 13:28:10

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:10

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:28:11

--- Main exception: Message ---
Wartość nie może być zerowa.
Nazwa parametru: source

--- Main exception: StackTrace ---
   w System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 556

--- Main exception: Source ---
System.Core

poniedziałek, 28 stycznia 2019 13:32:55

selectIssueList nie zawiera CRM-75069

poniedziałek, 28 stycznia 2019 13:33:01

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:33:01

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 13:42:19

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 13:42:19

selectIssueList nie zawiera CRM-75069

poniedziałek, 28 stycznia 2019 13:42:20

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17938 - 312198

poniedziałek, 28 stycznia 2019 13:42:20

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17936 - 312178

poniedziałek, 28 stycznia 2019 13:42:20

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17935 - 312177

poniedziałek, 28 stycznia 2019 13:42:20

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17835 - 310817

poniedziałek, 28 stycznia 2019 13:42:20

Próbwa wpisania zdublowanej wartości GetActionForIssues: KKK-3893 - 311897

poniedziałek, 28 stycznia 2019 13:42:20

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-75067 - 312185

poniedziałek, 28 stycznia 2019 13:42:21

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-75066 - 312182

poniedziałek, 28 stycznia 2019 13:42:21

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-75064 - 312181

poniedziałek, 28 stycznia 2019 13:42:21

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-74840 - 310587

poniedziałek, 28 stycznia 2019 13:42:23

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:42:24

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17937 - 312189

poniedziałek, 28 stycznia 2019 13:42:24

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17932 - 312136

poniedziałek, 28 stycznia 2019 13:42:24

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17931 - 312128

poniedziałek, 28 stycznia 2019 13:42:24

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17930 - 312130

poniedziałek, 28 stycznia 2019 13:42:24

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17925 - 308726

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17924 - 312008

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17923 - 311997

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17919 - 311950

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17599 - 304127

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: ZCC-17245 - 309054

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: WIND-8049 - 307124

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: WIND-8021 - 311620

poniedziałek, 28 stycznia 2019 13:42:25

Próbwa wpisania zdublowanej wartości GetActionForIssues: WIND-7763 - 305145

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: WIND-7744 - 305144

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: INFOLINIA-6469 - 311793

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: INFOLINIA-6464 - 311556

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: INFOLINIA-6405 - 307919

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: INFOLINIA-6247 - 309066

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: INFOLINIA-6066 - 294312

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: INFOLINIA-5940 - 284024

poniedziałek, 28 stycznia 2019 13:42:26

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-75072 - 312203

poniedziałek, 28 stycznia 2019 13:42:27

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-75069 - 312191

poniedziałek, 28 stycznia 2019 13:42:27

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-75068 - 312190

poniedziałek, 28 stycznia 2019 13:42:27

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-75048 - 312096

poniedziałek, 28 stycznia 2019 13:42:27

Próbwa wpisania zdublowanej wartości GetActionForIssues: CRM-74952 - 311459

poniedziałek, 28 stycznia 2019 13:42:39

selectIssueList nie zawiera CRM-75069

poniedziałek, 28 stycznia 2019 13:42:39

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 13:42:43

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 13:53:19

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w Atlassian.Jira.Remote.JiraRestClient.<ExecuteRequestAsync>b__0[T](Task`1 responseTask) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 132
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
mscorlib

--- Inner exception 2: Message ---
Nie można połączyć się z serwerem zdalnym

--- Inner exception 2: StackTrace ---
   w Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestResponse response) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 689
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 2: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w Logic.Implementation.JiraIssues.ChangeDataModel(IEnumerable`1 issues, List`1& newModel, List`1& jiraUsers) w C:\CP\ParserGit\JiraParser\Logic\Implementation\JiraIssues.cs:wiersz 161
   w GUI.MainForm.GetAllIssuesFromJira(Object sener, EventArgs e) w C:\CP\ParserGit\JiraParser\GUI\MainForm.cs:wiersz 4657

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 13:53:24

--- Main exception: Message ---
Nie można połączyć się z serwerem zdalnym

--- Main exception: StackTrace ---
   w Atlassian.Jira.Remote.JiraRestClient.ExecuteRequest[T](Method method, String resource, Object requestBody) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 119
   w Atlassian.Jira.Remote.JiraRestClient.GetIssueTypes(String token, String projectId) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 822
   w Atlassian.Jira.Jira.<>c__DisplayClass16.<GetIssueTypes>b__12(String token) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 414
   w Atlassian.Jira.Jira.<>c__DisplayClass3c.<WithToken>b__3b(String t) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 658
   w Atlassian.Jira.Jira.WithToken[TResult](Func`3 function) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 706
   w Atlassian.Jira.Jira.GetIssueTypes(String projectKey) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 419
   w Logic.Implementation.JiraIssues.GetJiraIssuesTypes() w C:\CP\ParserGit\JiraParser\Logic\Implementation\JiraIssues.cs:wiersz 68
   w GUI.MainForm.<timer2_Tick>b__101_0() w C:\CP\ParserGit\JiraParser\GUI\MainForm.cs:wiersz 2658

--- Main exception: Source ---
Atlassian.Jira

poniedziałek, 28 stycznia 2019 13:54:00

--- Main exception: Message ---
Błędne Hasło JIRA dla użytkownika prekawek

--- Main exception: StackTrace ---


--- Main exception: Source ---


poniedziałek, 28 stycznia 2019 13:56:29

--- Main exception: Message ---
Nie można połączyć się z serwerem zdalnym

--- Main exception: StackTrace ---
   w Atlassian.Jira.Remote.JiraRestClient.ExecuteRequest[T](Method method, String resource, Object requestBody) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 119
   w Atlassian.Jira.Remote.JiraRestClient.GetIssueTypes(String token, String projectId) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 822
   w Atlassian.Jira.Jira.<>c__DisplayClass16.<GetIssueTypes>b__12(String token) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 414
   w Atlassian.Jira.Jira.<>c__DisplayClass3c.<WithToken>b__3b(String t) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 658
   w Atlassian.Jira.Jira.WithToken[TResult](Func`3 function) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 706
   w Atlassian.Jira.Jira.GetIssueTypes(String projectKey) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:wiersz 419
   w Logic.Implementation.JiraIssues.GetJiraIssuesTypes() w C:\CP\ParserGit\JiraParser\Logic\Implementation\JiraIssues.cs:wiersz 68
   w GUI.MainForm.<timer2_Tick>b__101_0() w C:\CP\ParserGit\JiraParser\GUI\MainForm.cs:wiersz 2658

--- Main exception: Source ---
Atlassian.Jira

poniedziałek, 28 stycznia 2019 13:59:58

--- Main exception: Message ---
Błędne Hasło JIRA dla użytkownika prekawek

--- Main exception: StackTrace ---


--- Main exception: Source ---


poniedziałek, 28 stycznia 2019 14:04:03

selectIssueList nie zawiera CRM-75068

poniedziałek, 28 stycznia 2019 14:04:03

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 14:10:00

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 14:10:00

selectIssueList nie zawiera CRM-75072

poniedziałek, 28 stycznia 2019 14:16:00

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 14:21:54

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 14:27:53

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 14:33:57

selectIssueList nie zawiera CRM-75070

poniedziałek, 28 stycznia 2019 14:45:35

selectIssueList nie zawiera ZCC-17937

poniedziałek, 28 stycznia 2019 14:45:35

selectIssueList nie zawiera ZCC-17938

poniedziałek, 28 stycznia 2019 14:51:30

selectIssueList nie zawiera ZCC-17938

poniedziałek, 28 stycznia 2019 14:51:33

selectIssueList nie zawiera ZCC-17937

poniedziałek, 28 stycznia 2019 15:03:23

Zgłoszenie ZCC-17940 dodano automatycznie o godzinie 2019-01-28 15:03:23!
poniedziałek, 28 stycznia 2019 15:03:26

addCommentJira string jiraKey ZCC-17940poniedziałek, 28 stycznia 2019 15:03:26

addCommentJira object sender, DoWorkEventArgs e ZCC-17940poniedziałek, 28 stycznia 2019 15:15:51

selectIssueList nie zawiera CRM-75074

poniedziałek, 28 stycznia 2019 15:15:51

selectIssueList nie zawiera ZCC-17940

poniedziałek, 28 stycznia 2019 15:15:51

selectIssueList nie zawiera ZCC-17939

poniedziałek, 28 stycznia 2019 15:15:51

selectIssueList nie zawiera ZCC-17941

poniedziałek, 28 stycznia 2019 15:21:23

Zgłoszenie CRM-75075 dodano automatycznie o godzinie 2019-01-28 15:21:23!
poniedziałek, 28 stycznia 2019 15:21:25

addCommentJira string jiraKey CRM-75075poniedziałek, 28 stycznia 2019 15:21:25

addCommentJira object sender, DoWorkEventArgs e CRM-75075poniedziałek, 28 stycznia 2019 15:21:43

Zgłoszenie CRM-75076 dodano automatycznie o godzinie 2019-01-28 15:21:43!
poniedziałek, 28 stycznia 2019 15:21:54

selectIssueList nie zawiera ZCC-17940

poniedziałek, 28 stycznia 2019 15:21:54

selectIssueList nie zawiera CRM-75074

poniedziałek, 28 stycznia 2019 15:21:54

selectIssueList nie zawiera ZCC-17941

poniedziałek, 28 stycznia 2019 15:21:54

selectIssueList nie zawiera ZCC-17939

poniedziałek, 28 stycznia 2019 15:21:58

addCommentJira string jiraKey CRM-75076poniedziałek, 28 stycznia 2019 15:21:58

addCommentJira object sender, DoWorkEventArgs e CRM-75076poniedziałek, 28 stycznia 2019 15:27:50

selectIssueList nie zawiera ZCC-17941

poniedziałek, 28 stycznia 2019 15:27:50

selectIssueList nie zawiera ZCC-17939

poniedziałek, 28 stycznia 2019 15:27:50

selectIssueList nie zawiera ZCC-17940

poniedziałek, 28 stycznia 2019 15:27:50

selectIssueList nie zawiera CRM-75074

poniedziałek, 28 stycznia 2019 15:33:50

selectIssueList nie zawiera ZCC-17940

poniedziałek, 28 stycznia 2019 15:33:50

selectIssueList nie zawiera ZCC-17939

poniedziałek, 28 stycznia 2019 15:33:50

selectIssueList nie zawiera ZCC-17941

poniedziałek, 28 stycznia 2019 15:33:50

selectIssueList nie zawiera CRM-75074

poniedziałek, 28 stycznia 2019 15:39:50

selectIssueList nie zawiera ZCC-17939

poniedziałek, 28 stycznia 2019 15:39:50

selectIssueList nie zawiera ZCC-17941

poniedziałek, 28 stycznia 2019 15:39:50

selectIssueList nie zawiera ZCC-17940

poniedziałek, 28 stycznia 2019 16:09:18

--- Main exception: Message ---
Nieprawidłowa operacja między wątkami: do formantu '' uzyskiwany jest dostęp z wątku innego niż wątek, w którym został utworzony.

--- Main exception: StackTrace ---
   w System.Windows.Forms.Control.get_Handle()
   w System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   w System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.ToolStripControlHost.OnBoundsChanged()
   w System.Windows.Forms.ToolStripItem.SetBounds(Rectangle bounds)
   w System.Windows.Forms.ToolStripItem.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.Layout.TableLayout.SetElementBounds(ContainerInfo containerInfo, RectangleF displayRectF)
   w System.Windows.Forms.Layout.TableLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   w System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   w System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.ToolStrip.OnLayout(LayoutEventArgs e)
   w System.Windows.Forms.StatusStrip.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   w System.Windows.Forms.ToolStripItem.InvalidateItemLayout(String affectedProperty, Boolean invalidatePainting)
   w System.Windows.Forms.ToolStripItem.OnTextChanged(EventArgs e)
   w System.Windows.Forms.ToolStripItem.set_Text(String value)
   w GUI.MainForm.slaReportLoad(Object sender, DoWorkEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 28

--- Main exception: Source ---
System.Windows.Forms

poniedziałek, 28 stycznia 2019 16:15:19

--- Main exception: Message ---
Nieprawidłowa operacja między wątkami: do formantu '' uzyskiwany jest dostęp z wątku innego niż wątek, w którym został utworzony.

--- Main exception: StackTrace ---
   w System.Windows.Forms.Control.get_Handle()
   w System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   w System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.ToolStripControlHost.OnBoundsChanged()
   w System.Windows.Forms.ToolStripItem.SetBounds(Rectangle bounds)
   w System.Windows.Forms.ToolStripItem.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.Layout.TableLayout.SetElementBounds(ContainerInfo containerInfo, RectangleF displayRectF)
   w System.Windows.Forms.Layout.TableLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   w System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   w System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.ToolStrip.OnLayout(LayoutEventArgs e)
   w System.Windows.Forms.StatusStrip.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   w System.Windows.Forms.ToolStripItem.InvalidateItemLayout(String affectedProperty, Boolean invalidatePainting)
   w System.Windows.Forms.ToolStripItem.OnTextChanged(EventArgs e)
   w System.Windows.Forms.ToolStripItem.set_Text(String value)
   w GUI.MainForm.slaReportLoad(Object sender, DoWorkEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 28

--- Main exception: Source ---
System.Windows.Forms

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:43

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:18:44

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:21:18

--- Main exception: Message ---
Nieprawidłowa operacja między wątkami: do formantu '' uzyskiwany jest dostęp z wątku innego niż wątek, w którym został utworzony.

--- Main exception: StackTrace ---
   w System.Windows.Forms.Control.get_Handle()
   w System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   w System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.ToolStripControlHost.OnBoundsChanged()
   w System.Windows.Forms.ToolStripItem.SetBounds(Rectangle bounds)
   w System.Windows.Forms.ToolStripItem.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.Layout.TableLayout.SetElementBounds(ContainerInfo containerInfo, RectangleF displayRectF)
   w System.Windows.Forms.Layout.TableLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   w System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   w System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.ToolStrip.OnLayout(LayoutEventArgs e)
   w System.Windows.Forms.StatusStrip.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   w System.Windows.Forms.ToolStripItem.InvalidateItemLayout(String affectedProperty, Boolean invalidatePainting)
   w System.Windows.Forms.ToolStripItem.OnTextChanged(EventArgs e)
   w System.Windows.Forms.ToolStripItem.set_Text(String value)
   w GUI.MainForm.slaReportLoad(Object sender, DoWorkEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 28

--- Main exception: Source ---
System.Windows.Forms

poniedziałek, 28 stycznia 2019 16:21:20

Zgłoszenie CRM-75077 dodano automatycznie o godzinie 2019-01-28 16:21:20!
poniedziałek, 28 stycznia 2019 16:21:23

addCommentJira string jiraKey CRM-75077poniedziałek, 28 stycznia 2019 16:21:23

addCommentJira object sender, DoWorkEventArgs e CRM-75077poniedziałek, 28 stycznia 2019 16:27:18

--- Main exception: Message ---
Nieprawidłowa operacja między wątkami: do formantu '' uzyskiwany jest dostęp z wątku innego niż wątek, w którym został utworzony.

--- Main exception: StackTrace ---
   w System.Windows.Forms.Control.get_Handle()
   w System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   w System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.ToolStripControlHost.OnBoundsChanged()
   w System.Windows.Forms.ToolStripItem.SetBounds(Rectangle bounds)
   w System.Windows.Forms.ToolStripItem.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
   w System.Windows.Forms.Layout.TableLayout.SetElementBounds(ContainerInfo containerInfo, RectangleF displayRectF)
   w System.Windows.Forms.Layout.TableLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   w System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   w System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.ToolStrip.OnLayout(LayoutEventArgs e)
   w System.Windows.Forms.StatusStrip.OnLayout(LayoutEventArgs levent)
   w System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   w System.Windows.Forms.ToolStripItem.InvalidateItemLayout(String affectedProperty, Boolean invalidatePainting)
   w System.Windows.Forms.ToolStripItem.OnTextChanged(EventArgs e)
   w System.Windows.Forms.ToolStripItem.set_Text(String value)
   w GUI.MainForm.slaReportLoad(Object sender, DoWorkEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 28

--- Main exception: Source ---
System.Windows.Forms

poniedziałek, 28 stycznia 2019 16:28:40

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:40

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:40

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:40

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:40

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:40

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:40

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:41

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:41

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:41

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:41

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:41

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:28:42

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:13

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:14

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 16:29:15

--- Main exception: Message ---
Wystąpił przynajmniej jeden błąd.

--- Inner exception 1: Message ---
Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

--- Inner exception 1: StackTrace ---
   w Atlassian.Jira.Issue.Initialize(RemoteIssue remoteIssue) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Issue.cs:wiersz 57
   w Atlassian.Jira.Remote.JiraRestClient.<GetIssueAsync>b__3(Task`1 task) w c:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:wiersz 184
   w System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()

--- Inner exception 1: Source ---
Atlassian.Jira

--- Main exception: StackTrace ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w GUI.MainForm.slaAutoAssigneTakenIssue(Object sender, RunWorkerCompletedEventArgs e) w C:\CP\ParserGit\JiraParser\GUI\SlaService.cs:wiersz 561

--- Main exception: Source ---
mscorlib

poniedziałek, 28 stycznia 2019 17:52:24

Automatyczny zapis nowego zgłoszenia Entities.BillingIssueDtoHelios [2019-01-28 17:52:24] 

poniedziałek, 28 stycznia 2019 17:52:30

Automatyczny zapis poprawny Entities.BillingIssueDtoHelios [2019-01-28 17:52:30] 

poniedziałek, 28 stycznia 2019 17:52:30

Modyfikacja treeItemponiedziałek, 28 stycznia 2019 17:52:30

Status Auto: False 

poniedziałek, 28 stycznia 2019 17:52:57

addCommentJira string jiraKey WIND-8057poniedziałek, 28 stycznia 2019 20:47:12

--- Main exception: Message ---
Przekroczono limit czasu nieaktywności (00:10:00).

--- Main exception: StackTrace ---

Server stack trace: 
   w System.ServiceModel.Channels.ReliableRequestSessionChannel.SyncRequest.WaitForReply(TimeSpan timeout)
   w System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   w System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   w System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   w System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   w System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   w System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   w System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   w DataLayer.HPDataService.IDataService4HP.ExecuteStoredProcedure(User user, String procedureName, String[] parameters, DatabaseName database)
   w DataLayer.Implementation.GatewayDaoWFS.ExecuteStoredProcedure(String procedureName, String[] parameters, DatabaseName database) w C:\CP\ParserGit\JiraParser\DataLayer\Implementation\GatewayDaoWFS.cs:wiersz 138

--- Main exception: Source ---
mscorlib

